#! /usr/bin/env bash

set -e

BACKUP_PATH="/git-backup"
RCLONE_CONFIG_FILE="/rclone.conf"

if [ ! -d "$BACKUP_PATH" ]; then
  echo "dir $BACKUP_PATH not exist"
  exit 1
fi
if [ ! -f "$RCLONE_CONFIG_FILE" ]; then
  echo "file $RCLONE_CONFIG_FILE not exist"
  exit 1
fi

targets=( $(grep -oP '(?<=^\[)\w+_alias(?=\]$)' "$RCLONE_CONFIG_FILE" || true) )
if [ ${#targets[*]} = 0 ]; then
  echo "no targets in $RCLONE_CONFIG_FILE"
  exit 1
fi

failed=false

set +e

for i in ${!targets[@]}; do
    target="${targets[$i]}"
    echo "backup to $target"
    if ! rclone --config "$RCLONE_CONFIG_FILE" --contimeout=3m --timeout=10m sync "$BACKUP_PATH" "$target:"; then
      failed=true
    else
      echo "target $target sync successfully"
    fi
done

[ "$failed" = "false" ]
