#! /usr/bin/env bash

set -e

DB_PATH="/data"
DB_NAME="db.sqlite3"
BACKUP_PATH="/git-backup"

if [ ! -d "$BACKUP_PATH" ]; then
  echo "dir $BACKUP_PATH not exist"
  exit 1
fi
if [ ! -f "$DB_PATH/$DB_NAME" ]; then
  echo "file $DB_PATH/$DB_NAME not exist"
  exit 1
fi

cd "$BACKUP_PATH"

[ -d ".git" ] || git init
git config user.name bitwarden-backup
git config user.email backup@bitwarden.com

sqlite3 "$DB_PATH/$DB_NAME" .dump > bitwarden.sql

if [ -n "$(git status --porcelain)" ]; then 
  git add bitwarden.sql
  COMMIT_MSG="$(date '+%Y-%m-%d %H:%M:%S')"
  git commit -m "$COMMIT_MSG"
else
  echo "clean repo"
  exit 1
fi
